# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - riskcodingchallenge

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@main

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'

    - name: Build with dotnet
      run: cd Risk.Server && dotnet build --configuration Release

    - name: dotnet publish
      run: cd Risk.Server && dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp

    - name: Azure Login
      uses: Azure/login@v1
      with:
        # Paste output of `az ad sp create-for-rbac` as value of secret variable: AZURE_CREDENTIALS
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        # Set this value to true to enable Azure PowerShell Login in addition to Az CLI login
        #enable-AzPSSession: true

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'riskcodingchallenge'
        slot-name: 'production'
        publish-profile: ${{ secrets.PUBLISH_PROFILE }}
        package: ${{env.DOTNET_ROOT}}/myapp 
